// Code generated by ent, DO NOT EDIT.

package disposition

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the disposition type in the database.
	Label = "disposition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAssetID holds the string denoting the asset_id field in the database.
	FieldAssetID = "asset_id"
	// FieldSerialNumber holds the string denoting the serial_number field in the database.
	FieldSerialNumber = "serial_number"
	// FieldManufacturer holds the string denoting the manufacturer field in the database.
	FieldManufacturer = "manufacturer"
	// FieldModelNumber holds the string denoting the model_number field in the database.
	FieldModelNumber = "model_number"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldPurchasePrice holds the string denoting the purchase_price field in the database.
	FieldPurchasePrice = "purchase_price"
	// FieldPurchaseDate holds the string denoting the purchase_date field in the database.
	FieldPurchaseDate = "purchase_date"
	// FieldPurchaseFrom holds the string denoting the purchase_from field in the database.
	FieldPurchaseFrom = "purchase_from"
	// FieldInsured holds the string denoting the insured field in the database.
	FieldInsured = "insured"
	// FieldIsLocation holds the string denoting the is_location field in the database.
	FieldIsLocation = "is_location"
	// FieldParentName holds the string denoting the parent_name field in the database.
	FieldParentName = "parent_name"
	// FieldDisposition holds the string denoting the disposition field in the database.
	FieldDisposition = "disposition"
	// FieldDispositionDate holds the string denoting the disposition_date field in the database.
	FieldDispositionDate = "disposition_date"
	// FieldRecorderID holds the string denoting the recorder_id field in the database.
	FieldRecorderID = "recorder_id"
	// FieldRecorderName holds the string denoting the recorder_name field in the database.
	FieldRecorderName = "recorder_name"
	// FieldRecipient holds the string denoting the recipient field in the database.
	FieldRecipient = "recipient"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// Table holds the table name of the disposition in the database.
	Table = "dispositions"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "dispositions"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "disposition_attachments"
	// AttachmentsInverseTable is the table name for the DispositionAttachment entity.
	// It exists in this package in order to avoid circular dependency with the "dispositionattachment" package.
	AttachmentsInverseTable = "disposition_attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "disposition_id"
)

// Columns holds all SQL columns for disposition fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldName,
	FieldAssetID,
	FieldSerialNumber,
	FieldManufacturer,
	FieldModelNumber,
	FieldQuantity,
	FieldPurchasePrice,
	FieldPurchaseDate,
	FieldPurchaseFrom,
	FieldInsured,
	FieldIsLocation,
	FieldParentName,
	FieldDisposition,
	FieldDispositionDate,
	FieldRecorderID,
	FieldRecorderName,
	FieldRecipient,
	FieldValue,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSerialNumber holds the default value on creation for the "serial_number" field.
	DefaultSerialNumber string
	// SerialNumberValidator is a validator for the "serial_number" field. It is called by the builders before save.
	SerialNumberValidator func(string) error
	// DefaultManufacturer holds the default value on creation for the "manufacturer" field.
	DefaultManufacturer string
	// ManufacturerValidator is a validator for the "manufacturer" field. It is called by the builders before save.
	ManufacturerValidator func(string) error
	// DefaultModelNumber holds the default value on creation for the "model_number" field.
	DefaultModelNumber string
	// ModelNumberValidator is a validator for the "model_number" field. It is called by the builders before save.
	ModelNumberValidator func(string) error
	// DefaultPurchasePrice holds the default value on creation for the "purchase_price" field.
	DefaultPurchasePrice float64
	// DefaultPurchaseFrom holds the default value on creation for the "purchase_from" field.
	DefaultPurchaseFrom string
	// DefaultInsured holds the default value on creation for the "insured" field.
	DefaultInsured bool
	// DefaultParentName holds the default value on creation for the "parent_name" field.
	DefaultParentName string
	// ParentNameValidator is a validator for the "parent_name" field. It is called by the builders before save.
	ParentNameValidator func(string) error
	// RecorderNameValidator is a validator for the "recorder_name" field. It is called by the builders before save.
	RecorderNameValidator func(string) error
	// DefaultRecipient holds the default value on creation for the "recipient" field.
	DefaultRecipient string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	NotesValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Disposition defines the type for the "disposition" enum field.
type Disposition string

// Disposition values.
const (
	DispositionSold         Disposition = "sold"
	DispositionDestroyed    Disposition = "destroyed"
	DispositionGivenAway    Disposition = "given_away"
	DispositionDonated      Disposition = "donated"
	DispositionLostOrStolen Disposition = "lost_or_stolen"
)

func (d Disposition) String() string {
	return string(d)
}

// DispositionValidator is a validator for the "disposition" field enum values. It is called by the builders before save.
func DispositionValidator(d Disposition) error {
	switch d {
	case DispositionSold, DispositionDestroyed, DispositionGivenAway, DispositionDonated, DispositionLostOrStolen:
		return nil
	default:
		return fmt.Errorf("disposition: invalid enum value for disposition field: %q", d)
	}
}

// OrderOption defines the ordering options for the Disposition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAssetID orders the results by the asset_id field.
func ByAssetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetID, opts...).ToFunc()
}

// BySerialNumber orders the results by the serial_number field.
func BySerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerialNumber, opts...).ToFunc()
}

// ByManufacturer orders the results by the manufacturer field.
func ByManufacturer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManufacturer, opts...).ToFunc()
}

// ByModelNumber orders the results by the model_number field.
func ByModelNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelNumber, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByPurchasePrice orders the results by the purchase_price field.
func ByPurchasePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchasePrice, opts...).ToFunc()
}

// ByPurchaseDate orders the results by the purchase_date field.
func ByPurchaseDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseDate, opts...).ToFunc()
}

// ByPurchaseFrom orders the results by the purchase_from field.
func ByPurchaseFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseFrom, opts...).ToFunc()
}

// ByInsured orders the results by the insured field.
func ByInsured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInsured, opts...).ToFunc()
}

// ByIsLocation orders the results by the is_location field.
func ByIsLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocation, opts...).ToFunc()
}

// ByParentName orders the results by the parent_name field.
func ByParentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentName, opts...).ToFunc()
}

// ByDisposition orders the results by the disposition field.
func ByDisposition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisposition, opts...).ToFunc()
}

// ByDispositionDate orders the results by the disposition_date field.
func ByDispositionDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispositionDate, opts...).ToFunc()
}

// ByRecorderID orders the results by the recorder_id field.
func ByRecorderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecorderID, opts...).ToFunc()
}

// ByRecorderName orders the results by the recorder_name field.
func ByRecorderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecorderName, opts...).ToFunc()
}

// ByRecipient orders the results by the recipient field.
func ByRecipient(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipient, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
