// Code generated by ent, DO NOT EDIT.

package disposition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldGroupID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldName, v))
}

// AssetID applies equality check predicate on the "asset_id" field. It's identical to AssetIDEQ.
func AssetID(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldAssetID, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldSerialNumber, v))
}

// Manufacturer applies equality check predicate on the "manufacturer" field. It's identical to ManufacturerEQ.
func Manufacturer(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldManufacturer, v))
}

// ModelNumber applies equality check predicate on the "model_number" field. It's identical to ModelNumberEQ.
func ModelNumber(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldModelNumber, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldQuantity, v))
}

// PurchasePrice applies equality check predicate on the "purchase_price" field. It's identical to PurchasePriceEQ.
func PurchasePrice(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchasePrice, v))
}

// PurchaseDate applies equality check predicate on the "purchase_date" field. It's identical to PurchaseDateEQ.
func PurchaseDate(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchaseDate, v))
}

// PurchaseFrom applies equality check predicate on the "purchase_from" field. It's identical to PurchaseFromEQ.
func PurchaseFrom(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchaseFrom, v))
}

// Insured applies equality check predicate on the "insured" field. It's identical to InsuredEQ.
func Insured(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldInsured, v))
}

// IsLocation applies equality check predicate on the "is_location" field. It's identical to IsLocationEQ.
func IsLocation(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldIsLocation, v))
}

// ParentName applies equality check predicate on the "parent_name" field. It's identical to ParentNameEQ.
func ParentName(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldParentName, v))
}

// DispositionDate applies equality check predicate on the "disposition_date" field. It's identical to DispositionDateEQ.
func DispositionDate(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldDispositionDate, v))
}

// RecorderID applies equality check predicate on the "recorder_id" field. It's identical to RecorderIDEQ.
func RecorderID(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecorderID, v))
}

// RecorderName applies equality check predicate on the "recorder_name" field. It's identical to RecorderNameEQ.
func RecorderName(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecorderName, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecipient, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldValue, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldGroupID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldName, v))
}

// AssetIDEQ applies the EQ predicate on the "asset_id" field.
func AssetIDEQ(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldAssetID, v))
}

// AssetIDNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIDNEQ(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldAssetID, v))
}

// AssetIDIn applies the In predicate on the "asset_id" field.
func AssetIDIn(vs ...int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldAssetID, vs...))
}

// AssetIDNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIDNotIn(vs ...int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldAssetID, vs...))
}

// AssetIDGT applies the GT predicate on the "asset_id" field.
func AssetIDGT(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldAssetID, v))
}

// AssetIDGTE applies the GTE predicate on the "asset_id" field.
func AssetIDGTE(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldAssetID, v))
}

// AssetIDLT applies the LT predicate on the "asset_id" field.
func AssetIDLT(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldAssetID, v))
}

// AssetIDLTE applies the LTE predicate on the "asset_id" field.
func AssetIDLTE(v int64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldAssetID, v))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldSerialNumber, v))
}

// ManufacturerEQ applies the EQ predicate on the "manufacturer" field.
func ManufacturerEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldManufacturer, v))
}

// ManufacturerNEQ applies the NEQ predicate on the "manufacturer" field.
func ManufacturerNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldManufacturer, v))
}

// ManufacturerIn applies the In predicate on the "manufacturer" field.
func ManufacturerIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldManufacturer, vs...))
}

// ManufacturerNotIn applies the NotIn predicate on the "manufacturer" field.
func ManufacturerNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldManufacturer, vs...))
}

// ManufacturerGT applies the GT predicate on the "manufacturer" field.
func ManufacturerGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldManufacturer, v))
}

// ManufacturerGTE applies the GTE predicate on the "manufacturer" field.
func ManufacturerGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldManufacturer, v))
}

// ManufacturerLT applies the LT predicate on the "manufacturer" field.
func ManufacturerLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldManufacturer, v))
}

// ManufacturerLTE applies the LTE predicate on the "manufacturer" field.
func ManufacturerLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldManufacturer, v))
}

// ManufacturerContains applies the Contains predicate on the "manufacturer" field.
func ManufacturerContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldManufacturer, v))
}

// ManufacturerHasPrefix applies the HasPrefix predicate on the "manufacturer" field.
func ManufacturerHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldManufacturer, v))
}

// ManufacturerHasSuffix applies the HasSuffix predicate on the "manufacturer" field.
func ManufacturerHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldManufacturer, v))
}

// ManufacturerEqualFold applies the EqualFold predicate on the "manufacturer" field.
func ManufacturerEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldManufacturer, v))
}

// ManufacturerContainsFold applies the ContainsFold predicate on the "manufacturer" field.
func ManufacturerContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldManufacturer, v))
}

// ModelNumberEQ applies the EQ predicate on the "model_number" field.
func ModelNumberEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldModelNumber, v))
}

// ModelNumberNEQ applies the NEQ predicate on the "model_number" field.
func ModelNumberNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldModelNumber, v))
}

// ModelNumberIn applies the In predicate on the "model_number" field.
func ModelNumberIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldModelNumber, vs...))
}

// ModelNumberNotIn applies the NotIn predicate on the "model_number" field.
func ModelNumberNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldModelNumber, vs...))
}

// ModelNumberGT applies the GT predicate on the "model_number" field.
func ModelNumberGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldModelNumber, v))
}

// ModelNumberGTE applies the GTE predicate on the "model_number" field.
func ModelNumberGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldModelNumber, v))
}

// ModelNumberLT applies the LT predicate on the "model_number" field.
func ModelNumberLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldModelNumber, v))
}

// ModelNumberLTE applies the LTE predicate on the "model_number" field.
func ModelNumberLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldModelNumber, v))
}

// ModelNumberContains applies the Contains predicate on the "model_number" field.
func ModelNumberContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldModelNumber, v))
}

// ModelNumberHasPrefix applies the HasPrefix predicate on the "model_number" field.
func ModelNumberHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldModelNumber, v))
}

// ModelNumberHasSuffix applies the HasSuffix predicate on the "model_number" field.
func ModelNumberHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldModelNumber, v))
}

// ModelNumberEqualFold applies the EqualFold predicate on the "model_number" field.
func ModelNumberEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldModelNumber, v))
}

// ModelNumberContainsFold applies the ContainsFold predicate on the "model_number" field.
func ModelNumberContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldModelNumber, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldQuantity, v))
}

// PurchasePriceEQ applies the EQ predicate on the "purchase_price" field.
func PurchasePriceEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchasePrice, v))
}

// PurchasePriceNEQ applies the NEQ predicate on the "purchase_price" field.
func PurchasePriceNEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldPurchasePrice, v))
}

// PurchasePriceIn applies the In predicate on the "purchase_price" field.
func PurchasePriceIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldPurchasePrice, vs...))
}

// PurchasePriceNotIn applies the NotIn predicate on the "purchase_price" field.
func PurchasePriceNotIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldPurchasePrice, vs...))
}

// PurchasePriceGT applies the GT predicate on the "purchase_price" field.
func PurchasePriceGT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldPurchasePrice, v))
}

// PurchasePriceGTE applies the GTE predicate on the "purchase_price" field.
func PurchasePriceGTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldPurchasePrice, v))
}

// PurchasePriceLT applies the LT predicate on the "purchase_price" field.
func PurchasePriceLT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldPurchasePrice, v))
}

// PurchasePriceLTE applies the LTE predicate on the "purchase_price" field.
func PurchasePriceLTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldPurchasePrice, v))
}

// PurchaseDateEQ applies the EQ predicate on the "purchase_date" field.
func PurchaseDateEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchaseDate, v))
}

// PurchaseDateNEQ applies the NEQ predicate on the "purchase_date" field.
func PurchaseDateNEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldPurchaseDate, v))
}

// PurchaseDateIn applies the In predicate on the "purchase_date" field.
func PurchaseDateIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldPurchaseDate, vs...))
}

// PurchaseDateNotIn applies the NotIn predicate on the "purchase_date" field.
func PurchaseDateNotIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldPurchaseDate, vs...))
}

// PurchaseDateGT applies the GT predicate on the "purchase_date" field.
func PurchaseDateGT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldPurchaseDate, v))
}

// PurchaseDateGTE applies the GTE predicate on the "purchase_date" field.
func PurchaseDateGTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldPurchaseDate, v))
}

// PurchaseDateLT applies the LT predicate on the "purchase_date" field.
func PurchaseDateLT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldPurchaseDate, v))
}

// PurchaseDateLTE applies the LTE predicate on the "purchase_date" field.
func PurchaseDateLTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldPurchaseDate, v))
}

// PurchaseDateIsNil applies the IsNil predicate on the "purchase_date" field.
func PurchaseDateIsNil() predicate.Disposition {
	return predicate.Disposition(sql.FieldIsNull(FieldPurchaseDate))
}

// PurchaseDateNotNil applies the NotNil predicate on the "purchase_date" field.
func PurchaseDateNotNil() predicate.Disposition {
	return predicate.Disposition(sql.FieldNotNull(FieldPurchaseDate))
}

// PurchaseFromEQ applies the EQ predicate on the "purchase_from" field.
func PurchaseFromEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldPurchaseFrom, v))
}

// PurchaseFromNEQ applies the NEQ predicate on the "purchase_from" field.
func PurchaseFromNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldPurchaseFrom, v))
}

// PurchaseFromIn applies the In predicate on the "purchase_from" field.
func PurchaseFromIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldPurchaseFrom, vs...))
}

// PurchaseFromNotIn applies the NotIn predicate on the "purchase_from" field.
func PurchaseFromNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldPurchaseFrom, vs...))
}

// PurchaseFromGT applies the GT predicate on the "purchase_from" field.
func PurchaseFromGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldPurchaseFrom, v))
}

// PurchaseFromGTE applies the GTE predicate on the "purchase_from" field.
func PurchaseFromGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldPurchaseFrom, v))
}

// PurchaseFromLT applies the LT predicate on the "purchase_from" field.
func PurchaseFromLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldPurchaseFrom, v))
}

// PurchaseFromLTE applies the LTE predicate on the "purchase_from" field.
func PurchaseFromLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldPurchaseFrom, v))
}

// PurchaseFromContains applies the Contains predicate on the "purchase_from" field.
func PurchaseFromContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldPurchaseFrom, v))
}

// PurchaseFromHasPrefix applies the HasPrefix predicate on the "purchase_from" field.
func PurchaseFromHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldPurchaseFrom, v))
}

// PurchaseFromHasSuffix applies the HasSuffix predicate on the "purchase_from" field.
func PurchaseFromHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldPurchaseFrom, v))
}

// PurchaseFromEqualFold applies the EqualFold predicate on the "purchase_from" field.
func PurchaseFromEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldPurchaseFrom, v))
}

// PurchaseFromContainsFold applies the ContainsFold predicate on the "purchase_from" field.
func PurchaseFromContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldPurchaseFrom, v))
}

// InsuredEQ applies the EQ predicate on the "insured" field.
func InsuredEQ(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldInsured, v))
}

// InsuredNEQ applies the NEQ predicate on the "insured" field.
func InsuredNEQ(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldInsured, v))
}

// IsLocationEQ applies the EQ predicate on the "is_location" field.
func IsLocationEQ(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldIsLocation, v))
}

// IsLocationNEQ applies the NEQ predicate on the "is_location" field.
func IsLocationNEQ(v bool) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldIsLocation, v))
}

// ParentNameEQ applies the EQ predicate on the "parent_name" field.
func ParentNameEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldParentName, v))
}

// ParentNameNEQ applies the NEQ predicate on the "parent_name" field.
func ParentNameNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldParentName, v))
}

// ParentNameIn applies the In predicate on the "parent_name" field.
func ParentNameIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldParentName, vs...))
}

// ParentNameNotIn applies the NotIn predicate on the "parent_name" field.
func ParentNameNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldParentName, vs...))
}

// ParentNameGT applies the GT predicate on the "parent_name" field.
func ParentNameGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldParentName, v))
}

// ParentNameGTE applies the GTE predicate on the "parent_name" field.
func ParentNameGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldParentName, v))
}

// ParentNameLT applies the LT predicate on the "parent_name" field.
func ParentNameLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldParentName, v))
}

// ParentNameLTE applies the LTE predicate on the "parent_name" field.
func ParentNameLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldParentName, v))
}

// ParentNameContains applies the Contains predicate on the "parent_name" field.
func ParentNameContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldParentName, v))
}

// ParentNameHasPrefix applies the HasPrefix predicate on the "parent_name" field.
func ParentNameHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldParentName, v))
}

// ParentNameHasSuffix applies the HasSuffix predicate on the "parent_name" field.
func ParentNameHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldParentName, v))
}

// ParentNameEqualFold applies the EqualFold predicate on the "parent_name" field.
func ParentNameEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldParentName, v))
}

// ParentNameContainsFold applies the ContainsFold predicate on the "parent_name" field.
func ParentNameContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldParentName, v))
}

// DispositionEQ applies the EQ predicate on the "disposition" field.
func DispositionEQ(v Disposition) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldDisposition, v))
}

// DispositionNEQ applies the NEQ predicate on the "disposition" field.
func DispositionNEQ(v Disposition) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldDisposition, v))
}

// DispositionIn applies the In predicate on the "disposition" field.
func DispositionIn(vs ...Disposition) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldDisposition, vs...))
}

// DispositionNotIn applies the NotIn predicate on the "disposition" field.
func DispositionNotIn(vs ...Disposition) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldDisposition, vs...))
}

// DispositionDateEQ applies the EQ predicate on the "disposition_date" field.
func DispositionDateEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldDispositionDate, v))
}

// DispositionDateNEQ applies the NEQ predicate on the "disposition_date" field.
func DispositionDateNEQ(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldDispositionDate, v))
}

// DispositionDateIn applies the In predicate on the "disposition_date" field.
func DispositionDateIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldDispositionDate, vs...))
}

// DispositionDateNotIn applies the NotIn predicate on the "disposition_date" field.
func DispositionDateNotIn(vs ...time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldDispositionDate, vs...))
}

// DispositionDateGT applies the GT predicate on the "disposition_date" field.
func DispositionDateGT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldDispositionDate, v))
}

// DispositionDateGTE applies the GTE predicate on the "disposition_date" field.
func DispositionDateGTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldDispositionDate, v))
}

// DispositionDateLT applies the LT predicate on the "disposition_date" field.
func DispositionDateLT(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldDispositionDate, v))
}

// DispositionDateLTE applies the LTE predicate on the "disposition_date" field.
func DispositionDateLTE(v time.Time) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldDispositionDate, v))
}

// RecorderIDEQ applies the EQ predicate on the "recorder_id" field.
func RecorderIDEQ(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecorderID, v))
}

// RecorderIDNEQ applies the NEQ predicate on the "recorder_id" field.
func RecorderIDNEQ(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldRecorderID, v))
}

// RecorderIDIn applies the In predicate on the "recorder_id" field.
func RecorderIDIn(vs ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldRecorderID, vs...))
}

// RecorderIDNotIn applies the NotIn predicate on the "recorder_id" field.
func RecorderIDNotIn(vs ...uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldRecorderID, vs...))
}

// RecorderIDGT applies the GT predicate on the "recorder_id" field.
func RecorderIDGT(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldRecorderID, v))
}

// RecorderIDGTE applies the GTE predicate on the "recorder_id" field.
func RecorderIDGTE(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldRecorderID, v))
}

// RecorderIDLT applies the LT predicate on the "recorder_id" field.
func RecorderIDLT(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldRecorderID, v))
}

// RecorderIDLTE applies the LTE predicate on the "recorder_id" field.
func RecorderIDLTE(v uuid.UUID) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldRecorderID, v))
}

// RecorderNameEQ applies the EQ predicate on the "recorder_name" field.
func RecorderNameEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecorderName, v))
}

// RecorderNameNEQ applies the NEQ predicate on the "recorder_name" field.
func RecorderNameNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldRecorderName, v))
}

// RecorderNameIn applies the In predicate on the "recorder_name" field.
func RecorderNameIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldRecorderName, vs...))
}

// RecorderNameNotIn applies the NotIn predicate on the "recorder_name" field.
func RecorderNameNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldRecorderName, vs...))
}

// RecorderNameGT applies the GT predicate on the "recorder_name" field.
func RecorderNameGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldRecorderName, v))
}

// RecorderNameGTE applies the GTE predicate on the "recorder_name" field.
func RecorderNameGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldRecorderName, v))
}

// RecorderNameLT applies the LT predicate on the "recorder_name" field.
func RecorderNameLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldRecorderName, v))
}

// RecorderNameLTE applies the LTE predicate on the "recorder_name" field.
func RecorderNameLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldRecorderName, v))
}

// RecorderNameContains applies the Contains predicate on the "recorder_name" field.
func RecorderNameContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldRecorderName, v))
}

// RecorderNameHasPrefix applies the HasPrefix predicate on the "recorder_name" field.
func RecorderNameHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldRecorderName, v))
}

// RecorderNameHasSuffix applies the HasSuffix predicate on the "recorder_name" field.
func RecorderNameHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldRecorderName, v))
}

// RecorderNameEqualFold applies the EqualFold predicate on the "recorder_name" field.
func RecorderNameEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldRecorderName, v))
}

// RecorderNameContainsFold applies the ContainsFold predicate on the "recorder_name" field.
func RecorderNameContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldRecorderName, v))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldRecipient, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.Disposition {
	return predicate.Disposition(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.Disposition {
	return predicate.Disposition(sql.FieldNotNull(FieldValue))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Disposition {
	return predicate.Disposition(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Disposition {
	return predicate.Disposition(sql.FieldContainsFold(FieldNotes, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Disposition {
	return predicate.Disposition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Disposition {
	return predicate.Disposition(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Disposition {
	return predicate.Disposition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.DispositionAttachment) predicate.Disposition {
	return predicate.Disposition(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Disposition) predicate.Disposition {
	return predicate.Disposition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Disposition) predicate.Disposition {
	return predicate.Disposition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Disposition) predicate.Disposition {
	return predicate.Disposition(sql.NotPredicates(p))
}
