// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/disposition"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// Disposition is the model entity for the Disposition schema.
type Disposition struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID int64 `json:"asset_id,omitempty"`
	// SerialNumber holds the value of the "serial_number" field.
	SerialNumber string `json:"serial_number,omitempty"`
	// Manufacturer holds the value of the "manufacturer" field.
	Manufacturer string `json:"manufacturer,omitempty"`
	// ModelNumber holds the value of the "model_number" field.
	ModelNumber string `json:"model_number,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// PurchasePrice holds the value of the "purchase_price" field.
	PurchasePrice float64 `json:"purchase_price,omitempty"`
	// PurchaseDate holds the value of the "purchase_date" field.
	PurchaseDate *time.Time `json:"purchase_date,omitempty"`
	// PurchaseFrom holds the value of the "purchase_from" field.
	PurchaseFrom string `json:"purchase_from,omitempty"`
	// Insured holds the value of the "insured" field.
	Insured bool `json:"insured,omitempty"`
	// IsLocation holds the value of the "is_location" field.
	IsLocation bool `json:"is_location,omitempty"`
	// ParentName holds the value of the "parent_name" field.
	ParentName string `json:"parent_name,omitempty"`
	// Disposition holds the value of the "disposition" field.
	Disposition disposition.Disposition `json:"disposition,omitempty"`
	// DispositionDate holds the value of the "disposition_date" field.
	DispositionDate time.Time `json:"disposition_date,omitempty"`
	// RecorderID holds the value of the "recorder_id" field.
	RecorderID uuid.UUID `json:"recorder_id,omitempty"`
	// RecorderName holds the value of the "recorder_name" field.
	RecorderName string `json:"recorder_name,omitempty"`
	// Recipient holds the value of the "recipient" field.
	Recipient string `json:"recipient,omitempty"`
	// Value holds the value of the "value" field.
	Value *float64 `json:"value,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DispositionQuery when eager-loading is set.
	Edges        DispositionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DispositionEdges holds the relations/edges for other nodes in the graph.
type DispositionEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*DispositionAttachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DispositionEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e DispositionEdges) AttachmentsOrErr() ([]*DispositionAttachment, error) {
	if e.loadedTypes[1] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Disposition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case disposition.FieldInsured, disposition.FieldIsLocation:
			values[i] = new(sql.NullBool)
		case disposition.FieldQuantity, disposition.FieldPurchasePrice, disposition.FieldValue:
			values[i] = new(sql.NullFloat64)
		case disposition.FieldAssetID:
			values[i] = new(sql.NullInt64)
		case disposition.FieldName, disposition.FieldSerialNumber, disposition.FieldManufacturer, disposition.FieldModelNumber, disposition.FieldPurchaseFrom, disposition.FieldParentName, disposition.FieldDisposition, disposition.FieldRecorderName, disposition.FieldRecipient, disposition.FieldNotes:
			values[i] = new(sql.NullString)
		case disposition.FieldCreatedAt, disposition.FieldUpdatedAt, disposition.FieldPurchaseDate, disposition.FieldDispositionDate:
			values[i] = new(sql.NullTime)
		case disposition.FieldID, disposition.FieldGroupID, disposition.FieldRecorderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Disposition fields.
func (_m *Disposition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case disposition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case disposition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case disposition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case disposition.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case disposition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case disposition.FieldAssetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = value.Int64
			}
		case disposition.FieldSerialNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field serial_number", values[i])
			} else if value.Valid {
				_m.SerialNumber = value.String
			}
		case disposition.FieldManufacturer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manufacturer", values[i])
			} else if value.Valid {
				_m.Manufacturer = value.String
			}
		case disposition.FieldModelNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_number", values[i])
			} else if value.Valid {
				_m.ModelNumber = value.String
			}
		case disposition.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case disposition.FieldPurchasePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_price", values[i])
			} else if value.Valid {
				_m.PurchasePrice = value.Float64
			}
		case disposition.FieldPurchaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_date", values[i])
			} else if value.Valid {
				_m.PurchaseDate = new(time.Time)
				*_m.PurchaseDate = value.Time
			}
		case disposition.FieldPurchaseFrom:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_from", values[i])
			} else if value.Valid {
				_m.PurchaseFrom = value.String
			}
		case disposition.FieldInsured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field insured", values[i])
			} else if value.Valid {
				_m.Insured = value.Bool
			}
		case disposition.FieldIsLocation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_location", values[i])
			} else if value.Valid {
				_m.IsLocation = value.Bool
			}
		case disposition.FieldParentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_name", values[i])
			} else if value.Valid {
				_m.ParentName = value.String
			}
		case disposition.FieldDisposition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disposition", values[i])
			} else if value.Valid {
				_m.Disposition = disposition.Disposition(value.String)
			}
		case disposition.FieldDispositionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disposition_date", values[i])
			} else if value.Valid {
				_m.DispositionDate = value.Time
			}
		case disposition.FieldRecorderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field recorder_id", values[i])
			} else if value != nil {
				_m.RecorderID = *value
			}
		case disposition.FieldRecorderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recorder_name", values[i])
			} else if value.Valid {
				_m.RecorderName = value.String
			}
		case disposition.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				_m.Recipient = value.String
			}
		case disposition.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = new(float64)
				*_m.Value = value.Float64
			}
		case disposition.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Disposition.
// This includes values selected through modifiers, order, etc.
func (_m *Disposition) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Disposition entity.
func (_m *Disposition) QueryGroup() *GroupQuery {
	return NewDispositionClient(_m.config).QueryGroup(_m)
}

// QueryAttachments queries the "attachments" edge of the Disposition entity.
func (_m *Disposition) QueryAttachments() *DispositionAttachmentQuery {
	return NewDispositionClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this Disposition.
// Note that you need to call Disposition.Unwrap() before calling this method if this Disposition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Disposition) Update() *DispositionUpdateOne {
	return NewDispositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Disposition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Disposition) Unwrap() *Disposition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Disposition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Disposition) String() string {
	var builder strings.Builder
	builder.WriteString("Disposition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("asset_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssetID))
	builder.WriteString(", ")
	builder.WriteString("serial_number=")
	builder.WriteString(_m.SerialNumber)
	builder.WriteString(", ")
	builder.WriteString("manufacturer=")
	builder.WriteString(_m.Manufacturer)
	builder.WriteString(", ")
	builder.WriteString("model_number=")
	builder.WriteString(_m.ModelNumber)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("purchase_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.PurchasePrice))
	builder.WriteString(", ")
	if v := _m.PurchaseDate; v != nil {
		builder.WriteString("purchase_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("purchase_from=")
	builder.WriteString(_m.PurchaseFrom)
	builder.WriteString(", ")
	builder.WriteString("insured=")
	builder.WriteString(fmt.Sprintf("%v", _m.Insured))
	builder.WriteString(", ")
	builder.WriteString("is_location=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsLocation))
	builder.WriteString(", ")
	builder.WriteString("parent_name=")
	builder.WriteString(_m.ParentName)
	builder.WriteString(", ")
	builder.WriteString("disposition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Disposition))
	builder.WriteString(", ")
	builder.WriteString("disposition_date=")
	builder.WriteString(_m.DispositionDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("recorder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecorderID))
	builder.WriteString(", ")
	builder.WriteString("recorder_name=")
	builder.WriteString(_m.RecorderName)
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(_m.Recipient)
	builder.WriteString(", ")
	if v := _m.Value; v != nil {
		builder.WriteString("value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// Dispositions is a parsable slice of Disposition.
type Dispositions []*Disposition
