// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/disposition"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/dispositionattachment"
)

// DispositionAttachmentCreate is the builder for creating a DispositionAttachment entity.
type DispositionAttachmentCreate struct {
	config
	mutation *DispositionAttachmentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DispositionAttachmentCreate) SetCreatedAt(v time.Time) *DispositionAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DispositionAttachmentCreate) SetNillableCreatedAt(v *time.Time) *DispositionAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DispositionAttachmentCreate) SetUpdatedAt(v time.Time) *DispositionAttachmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DispositionAttachmentCreate) SetNillableUpdatedAt(v *time.Time) *DispositionAttachmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDispositionID sets the "disposition_id" field.
func (_c *DispositionAttachmentCreate) SetDispositionID(v uuid.UUID) *DispositionAttachmentCreate {
	_c.mutation.SetDispositionID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *DispositionAttachmentCreate) SetType(v dispositionattachment.Type) *DispositionAttachmentCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DispositionAttachmentCreate) SetTitle(v string) *DispositionAttachmentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *DispositionAttachmentCreate) SetNillableTitle(v *string) *DispositionAttachmentCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *DispositionAttachmentCreate) SetPath(v string) *DispositionAttachmentCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *DispositionAttachmentCreate) SetMimeType(v string) *DispositionAttachmentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *DispositionAttachmentCreate) SetNillableMimeType(v *string) *DispositionAttachmentCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DispositionAttachmentCreate) SetID(v uuid.UUID) *DispositionAttachmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DispositionAttachmentCreate) SetNillableID(v *uuid.UUID) *DispositionAttachmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDisposition sets the "disposition" edge to the Disposition entity.
func (_c *DispositionAttachmentCreate) SetDisposition(v *Disposition) *DispositionAttachmentCreate {
	return _c.SetDispositionID(v.ID)
}

// Mutation returns the DispositionAttachmentMutation object of the builder.
func (_c *DispositionAttachmentCreate) Mutation() *DispositionAttachmentMutation {
	return _c.mutation
}

// Save creates the DispositionAttachment in the database.
func (_c *DispositionAttachmentCreate) Save(ctx context.Context) (*DispositionAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DispositionAttachmentCreate) SaveX(ctx context.Context) *DispositionAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispositionAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispositionAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DispositionAttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dispositionattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dispositionattachment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := dispositionattachment.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		v := dispositionattachment.DefaultMimeType
		_c.mutation.SetMimeType(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dispositionattachment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DispositionAttachmentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DispositionAttachment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DispositionAttachment.updated_at"`)}
	}
	if _, ok := _c.mutation.DispositionID(); !ok {
		return &ValidationError{Name: "disposition_id", err: errors.New(`ent: missing required field "DispositionAttachment.disposition_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "DispositionAttachment.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := dispositionattachment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DispositionAttachment.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "DispositionAttachment.title"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "DispositionAttachment.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := dispositionattachment.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "DispositionAttachment.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "DispositionAttachment.mime_type"`)}
	}
	if len(_c.mutation.DispositionIDs()) == 0 {
		return &ValidationError{Name: "disposition", err: errors.New(`ent: missing required edge "DispositionAttachment.disposition"`)}
	}
	return nil
}

func (_c *DispositionAttachmentCreate) sqlSave(ctx context.Context) (*DispositionAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DispositionAttachmentCreate) createSpec() (*DispositionAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &DispositionAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dispositionattachment.Table, sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dispositionattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dispositionattachment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(dispositionattachment.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(dispositionattachment.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(dispositionattachment.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(dispositionattachment.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if nodes := _c.mutation.DispositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dispositionattachment.DispositionTable,
			Columns: []string{dispositionattachment.DispositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(disposition.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DispositionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DispositionAttachmentCreateBulk is the builder for creating many DispositionAttachment entities in bulk.
type DispositionAttachmentCreateBulk struct {
	config
	err      error
	builders []*DispositionAttachmentCreate
}

// Save creates the DispositionAttachment entities in the database.
func (_c *DispositionAttachmentCreateBulk) Save(ctx context.Context) ([]*DispositionAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DispositionAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DispositionAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DispositionAttachmentCreateBulk) SaveX(ctx context.Context) []*DispositionAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispositionAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispositionAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
