// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/disposition"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/dispositionattachment"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// DispositionUpdate is the builder for updating Disposition entities.
type DispositionUpdate struct {
	config
	hooks    []Hook
	mutation *DispositionMutation
}

// Where appends a list predicates to the DispositionUpdate builder.
func (_u *DispositionUpdate) Where(ps ...predicate.Disposition) *DispositionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispositionUpdate) SetUpdatedAt(v time.Time) *DispositionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DispositionUpdate) SetGroupID(v uuid.UUID) *DispositionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DispositionUpdate) SetNillableGroupID(v *uuid.UUID) *DispositionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DispositionUpdate) SetGroup(v *Group) *DispositionUpdate {
	return _u.SetGroupID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the DispositionAttachment entity by IDs.
func (_u *DispositionUpdate) AddAttachmentIDs(ids ...uuid.UUID) *DispositionUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the DispositionAttachment entity.
func (_u *DispositionUpdate) AddAttachments(v ...*DispositionAttachment) *DispositionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the DispositionMutation object of the builder.
func (_u *DispositionUpdate) Mutation() *DispositionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DispositionUpdate) ClearGroup() *DispositionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAttachments clears all "attachments" edges to the DispositionAttachment entity.
func (_u *DispositionUpdate) ClearAttachments() *DispositionUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to DispositionAttachment entities by IDs.
func (_u *DispositionUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *DispositionUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to DispositionAttachment entities.
func (_u *DispositionUpdate) RemoveAttachments(v ...*DispositionAttachment) *DispositionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DispositionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispositionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DispositionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispositionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispositionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := disposition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispositionUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Disposition.group"`)
	}
	return nil
}

func (_u *DispositionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(disposition.Table, disposition.Columns, sqlgraph.NewFieldSpec(disposition.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(disposition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(disposition.FieldPurchaseDate, field.TypeTime)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(disposition.FieldValue, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disposition.GroupTable,
			Columns: []string{disposition.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disposition.GroupTable,
			Columns: []string{disposition.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DispositionUpdateOne is the builder for updating a single Disposition entity.
type DispositionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DispositionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispositionUpdateOne) SetUpdatedAt(v time.Time) *DispositionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DispositionUpdateOne) SetGroupID(v uuid.UUID) *DispositionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DispositionUpdateOne) SetNillableGroupID(v *uuid.UUID) *DispositionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DispositionUpdateOne) SetGroup(v *Group) *DispositionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the DispositionAttachment entity by IDs.
func (_u *DispositionUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *DispositionUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the DispositionAttachment entity.
func (_u *DispositionUpdateOne) AddAttachments(v ...*DispositionAttachment) *DispositionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the DispositionMutation object of the builder.
func (_u *DispositionUpdateOne) Mutation() *DispositionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DispositionUpdateOne) ClearGroup() *DispositionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAttachments clears all "attachments" edges to the DispositionAttachment entity.
func (_u *DispositionUpdateOne) ClearAttachments() *DispositionUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to DispositionAttachment entities by IDs.
func (_u *DispositionUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *DispositionUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to DispositionAttachment entities.
func (_u *DispositionUpdateOne) RemoveAttachments(v ...*DispositionAttachment) *DispositionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the DispositionUpdate builder.
func (_u *DispositionUpdateOne) Where(ps ...predicate.Disposition) *DispositionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DispositionUpdateOne) Select(field string, fields ...string) *DispositionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Disposition entity.
func (_u *DispositionUpdateOne) Save(ctx context.Context) (*Disposition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispositionUpdateOne) SaveX(ctx context.Context) *Disposition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DispositionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispositionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispositionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := disposition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispositionUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Disposition.group"`)
	}
	return nil
}

func (_u *DispositionUpdateOne) sqlSave(ctx context.Context) (_node *Disposition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(disposition.Table, disposition.Columns, sqlgraph.NewFieldSpec(disposition.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Disposition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, disposition.FieldID)
		for _, f := range fields {
			if !disposition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != disposition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(disposition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(disposition.FieldPurchaseDate, field.TypeTime)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(disposition.FieldValue, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disposition.GroupTable,
			Columns: []string{disposition.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disposition.GroupTable,
			Columns: []string{disposition.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Disposition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
