// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/disposition"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/dispositionattachment"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// DispositionCreate is the builder for creating a Disposition entity.
type DispositionCreate struct {
	config
	mutation *DispositionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DispositionCreate) SetCreatedAt(v time.Time) *DispositionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableCreatedAt(v *time.Time) *DispositionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DispositionCreate) SetUpdatedAt(v time.Time) *DispositionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableUpdatedAt(v *time.Time) *DispositionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DispositionCreate) SetGroupID(v uuid.UUID) *DispositionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DispositionCreate) SetName(v string) *DispositionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAssetID sets the "asset_id" field.
func (_c *DispositionCreate) SetAssetID(v int64) *DispositionCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *DispositionCreate) SetSerialNumber(v string) *DispositionCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableSerialNumber(v *string) *DispositionCreate {
	if v != nil {
		_c.SetSerialNumber(*v)
	}
	return _c
}

// SetManufacturer sets the "manufacturer" field.
func (_c *DispositionCreate) SetManufacturer(v string) *DispositionCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableManufacturer(v *string) *DispositionCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetModelNumber sets the "model_number" field.
func (_c *DispositionCreate) SetModelNumber(v string) *DispositionCreate {
	_c.mutation.SetModelNumber(v)
	return _c
}

// SetNillableModelNumber sets the "model_number" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableModelNumber(v *string) *DispositionCreate {
	if v != nil {
		_c.SetModelNumber(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *DispositionCreate) SetQuantity(v float64) *DispositionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetPurchasePrice sets the "purchase_price" field.
func (_c *DispositionCreate) SetPurchasePrice(v float64) *DispositionCreate {
	_c.mutation.SetPurchasePrice(v)
	return _c
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (_c *DispositionCreate) SetNillablePurchasePrice(v *float64) *DispositionCreate {
	if v != nil {
		_c.SetPurchasePrice(*v)
	}
	return _c
}

// SetPurchaseDate sets the "purchase_date" field.
func (_c *DispositionCreate) SetPurchaseDate(v time.Time) *DispositionCreate {
	_c.mutation.SetPurchaseDate(v)
	return _c
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_c *DispositionCreate) SetNillablePurchaseDate(v *time.Time) *DispositionCreate {
	if v != nil {
		_c.SetPurchaseDate(*v)
	}
	return _c
}

// SetPurchaseFrom sets the "purchase_from" field.
func (_c *DispositionCreate) SetPurchaseFrom(v string) *DispositionCreate {
	_c.mutation.SetPurchaseFrom(v)
	return _c
}

// SetNillablePurchaseFrom sets the "purchase_from" field if the given value is not nil.
func (_c *DispositionCreate) SetNillablePurchaseFrom(v *string) *DispositionCreate {
	if v != nil {
		_c.SetPurchaseFrom(*v)
	}
	return _c
}

// SetInsured sets the "insured" field.
func (_c *DispositionCreate) SetInsured(v bool) *DispositionCreate {
	_c.mutation.SetInsured(v)
	return _c
}

// SetNillableInsured sets the "insured" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableInsured(v *bool) *DispositionCreate {
	if v != nil {
		_c.SetInsured(*v)
	}
	return _c
}

// SetIsLocation sets the "is_location" field.
func (_c *DispositionCreate) SetIsLocation(v bool) *DispositionCreate {
	_c.mutation.SetIsLocation(v)
	return _c
}

// SetParentName sets the "parent_name" field.
func (_c *DispositionCreate) SetParentName(v string) *DispositionCreate {
	_c.mutation.SetParentName(v)
	return _c
}

// SetNillableParentName sets the "parent_name" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableParentName(v *string) *DispositionCreate {
	if v != nil {
		_c.SetParentName(*v)
	}
	return _c
}

// SetDisposition sets the "disposition" field.
func (_c *DispositionCreate) SetDisposition(v disposition.Disposition) *DispositionCreate {
	_c.mutation.SetDisposition(v)
	return _c
}

// SetDispositionDate sets the "disposition_date" field.
func (_c *DispositionCreate) SetDispositionDate(v time.Time) *DispositionCreate {
	_c.mutation.SetDispositionDate(v)
	return _c
}

// SetRecorderID sets the "recorder_id" field.
func (_c *DispositionCreate) SetRecorderID(v uuid.UUID) *DispositionCreate {
	_c.mutation.SetRecorderID(v)
	return _c
}

// SetRecorderName sets the "recorder_name" field.
func (_c *DispositionCreate) SetRecorderName(v string) *DispositionCreate {
	_c.mutation.SetRecorderName(v)
	return _c
}

// SetRecipient sets the "recipient" field.
func (_c *DispositionCreate) SetRecipient(v string) *DispositionCreate {
	_c.mutation.SetRecipient(v)
	return _c
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableRecipient(v *string) *DispositionCreate {
	if v != nil {
		_c.SetRecipient(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *DispositionCreate) SetValue(v float64) *DispositionCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableValue(v *float64) *DispositionCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *DispositionCreate) SetNotes(v string) *DispositionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableNotes(v *string) *DispositionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DispositionCreate) SetID(v uuid.UUID) *DispositionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DispositionCreate) SetNillableID(v *uuid.UUID) *DispositionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *DispositionCreate) SetGroup(v *Group) *DispositionCreate {
	return _c.SetGroupID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the DispositionAttachment entity by IDs.
func (_c *DispositionCreate) AddAttachmentIDs(ids ...uuid.UUID) *DispositionCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the DispositionAttachment entity.
func (_c *DispositionCreate) AddAttachments(v ...*DispositionAttachment) *DispositionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the DispositionMutation object of the builder.
func (_c *DispositionCreate) Mutation() *DispositionMutation {
	return _c.mutation
}

// Save creates the Disposition in the database.
func (_c *DispositionCreate) Save(ctx context.Context) (*Disposition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DispositionCreate) SaveX(ctx context.Context) *Disposition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DispositionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := disposition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := disposition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SerialNumber(); !ok {
		v := disposition.DefaultSerialNumber
		_c.mutation.SetSerialNumber(v)
	}
	if _, ok := _c.mutation.Manufacturer(); !ok {
		v := disposition.DefaultManufacturer
		_c.mutation.SetManufacturer(v)
	}
	if _, ok := _c.mutation.ModelNumber(); !ok {
		v := disposition.DefaultModelNumber
		_c.mutation.SetModelNumber(v)
	}
	if _, ok := _c.mutation.PurchasePrice(); !ok {
		v := disposition.DefaultPurchasePrice
		_c.mutation.SetPurchasePrice(v)
	}
	if _, ok := _c.mutation.PurchaseFrom(); !ok {
		v := disposition.DefaultPurchaseFrom
		_c.mutation.SetPurchaseFrom(v)
	}
	if _, ok := _c.mutation.Insured(); !ok {
		v := disposition.DefaultInsured
		_c.mutation.SetInsured(v)
	}
	if _, ok := _c.mutation.ParentName(); !ok {
		v := disposition.DefaultParentName
		_c.mutation.SetParentName(v)
	}
	if _, ok := _c.mutation.Recipient(); !ok {
		v := disposition.DefaultRecipient
		_c.mutation.SetRecipient(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := disposition.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := disposition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DispositionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Disposition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Disposition.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "Disposition.group_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Disposition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := disposition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Disposition.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssetID(); !ok {
		return &ValidationError{Name: "asset_id", err: errors.New(`ent: missing required field "Disposition.asset_id"`)}
	}
	if _, ok := _c.mutation.SerialNumber(); !ok {
		return &ValidationError{Name: "serial_number", err: errors.New(`ent: missing required field "Disposition.serial_number"`)}
	}
	if v, ok := _c.mutation.SerialNumber(); ok {
		if err := disposition.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Disposition.serial_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Manufacturer(); !ok {
		return &ValidationError{Name: "manufacturer", err: errors.New(`ent: missing required field "Disposition.manufacturer"`)}
	}
	if v, ok := _c.mutation.Manufacturer(); ok {
		if err := disposition.ManufacturerValidator(v); err != nil {
			return &ValidationError{Name: "manufacturer", err: fmt.Errorf(`ent: validator failed for field "Disposition.manufacturer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelNumber(); !ok {
		return &ValidationError{Name: "model_number", err: errors.New(`ent: missing required field "Disposition.model_number"`)}
	}
	if v, ok := _c.mutation.ModelNumber(); ok {
		if err := disposition.ModelNumberValidator(v); err != nil {
			return &ValidationError{Name: "model_number", err: fmt.Errorf(`ent: validator failed for field "Disposition.model_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Disposition.quantity"`)}
	}
	if _, ok := _c.mutation.PurchasePrice(); !ok {
		return &ValidationError{Name: "purchase_price", err: errors.New(`ent: missing required field "Disposition.purchase_price"`)}
	}
	if _, ok := _c.mutation.PurchaseFrom(); !ok {
		return &ValidationError{Name: "purchase_from", err: errors.New(`ent: missing required field "Disposition.purchase_from"`)}
	}
	if _, ok := _c.mutation.Insured(); !ok {
		return &ValidationError{Name: "insured", err: errors.New(`ent: missing required field "Disposition.insured"`)}
	}
	if _, ok := _c.mutation.IsLocation(); !ok {
		return &ValidationError{Name: "is_location", err: errors.New(`ent: missing required field "Disposition.is_location"`)}
	}
	if _, ok := _c.mutation.ParentName(); !ok {
		return &ValidationError{Name: "parent_name", err: errors.New(`ent: missing required field "Disposition.parent_name"`)}
	}
	if v, ok := _c.mutation.ParentName(); ok {
		if err := disposition.ParentNameValidator(v); err != nil {
			return &ValidationError{Name: "parent_name", err: fmt.Errorf(`ent: validator failed for field "Disposition.parent_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Disposition(); !ok {
		return &ValidationError{Name: "disposition", err: errors.New(`ent: missing required field "Disposition.disposition"`)}
	}
	if v, ok := _c.mutation.Disposition(); ok {
		if err := disposition.DispositionValidator(v); err != nil {
			return &ValidationError{Name: "disposition", err: fmt.Errorf(`ent: validator failed for field "Disposition.disposition": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DispositionDate(); !ok {
		return &ValidationError{Name: "disposition_date", err: errors.New(`ent: missing required field "Disposition.disposition_date"`)}
	}
	if _, ok := _c.mutation.RecorderID(); !ok {
		return &ValidationError{Name: "recorder_id", err: errors.New(`ent: missing required field "Disposition.recorder_id"`)}
	}
	if _, ok := _c.mutation.RecorderName(); !ok {
		return &ValidationError{Name: "recorder_name", err: errors.New(`ent: missing required field "Disposition.recorder_name"`)}
	}
	if v, ok := _c.mutation.RecorderName(); ok {
		if err := disposition.RecorderNameValidator(v); err != nil {
			return &ValidationError{Name: "recorder_name", err: fmt.Errorf(`ent: validator failed for field "Disposition.recorder_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "Disposition.recipient"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "Disposition.notes"`)}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := disposition.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Disposition.notes": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Disposition.group"`)}
	}
	return nil
}

func (_c *DispositionCreate) sqlSave(ctx context.Context) (*Disposition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DispositionCreate) createSpec() (*Disposition, *sqlgraph.CreateSpec) {
	var (
		_node = &Disposition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(disposition.Table, sqlgraph.NewFieldSpec(disposition.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(disposition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(disposition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(disposition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AssetID(); ok {
		_spec.SetField(disposition.FieldAssetID, field.TypeInt64, value)
		_node.AssetID = value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(disposition.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(disposition.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.ModelNumber(); ok {
		_spec.SetField(disposition.FieldModelNumber, field.TypeString, value)
		_node.ModelNumber = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(disposition.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.PurchasePrice(); ok {
		_spec.SetField(disposition.FieldPurchasePrice, field.TypeFloat64, value)
		_node.PurchasePrice = value
	}
	if value, ok := _c.mutation.PurchaseDate(); ok {
		_spec.SetField(disposition.FieldPurchaseDate, field.TypeTime, value)
		_node.PurchaseDate = &value
	}
	if value, ok := _c.mutation.PurchaseFrom(); ok {
		_spec.SetField(disposition.FieldPurchaseFrom, field.TypeString, value)
		_node.PurchaseFrom = value
	}
	if value, ok := _c.mutation.Insured(); ok {
		_spec.SetField(disposition.FieldInsured, field.TypeBool, value)
		_node.Insured = value
	}
	if value, ok := _c.mutation.IsLocation(); ok {
		_spec.SetField(disposition.FieldIsLocation, field.TypeBool, value)
		_node.IsLocation = value
	}
	if value, ok := _c.mutation.ParentName(); ok {
		_spec.SetField(disposition.FieldParentName, field.TypeString, value)
		_node.ParentName = value
	}
	if value, ok := _c.mutation.Disposition(); ok {
		_spec.SetField(disposition.FieldDisposition, field.TypeEnum, value)
		_node.Disposition = value
	}
	if value, ok := _c.mutation.DispositionDate(); ok {
		_spec.SetField(disposition.FieldDispositionDate, field.TypeTime, value)
		_node.DispositionDate = value
	}
	if value, ok := _c.mutation.RecorderID(); ok {
		_spec.SetField(disposition.FieldRecorderID, field.TypeUUID, value)
		_node.RecorderID = value
	}
	if value, ok := _c.mutation.RecorderName(); ok {
		_spec.SetField(disposition.FieldRecorderName, field.TypeString, value)
		_node.RecorderName = value
	}
	if value, ok := _c.mutation.Recipient(); ok {
		_spec.SetField(disposition.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(disposition.FieldValue, field.TypeFloat64, value)
		_node.Value = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(disposition.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   disposition.GroupTable,
			Columns: []string{disposition.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disposition.AttachmentsTable,
			Columns: []string{disposition.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DispositionCreateBulk is the builder for creating many Disposition entities in bulk.
type DispositionCreateBulk struct {
	config
	err      error
	builders []*DispositionCreate
}

// Save creates the Disposition entities in the database.
func (_c *DispositionCreateBulk) Save(ctx context.Context) ([]*Disposition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Disposition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DispositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DispositionCreateBulk) SaveX(ctx context.Context) []*Disposition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
