// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/dispositionattachment"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// DispositionAttachmentUpdate is the builder for updating DispositionAttachment entities.
type DispositionAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *DispositionAttachmentMutation
}

// Where appends a list predicates to the DispositionAttachmentUpdate builder.
func (_u *DispositionAttachmentUpdate) Where(ps ...predicate.DispositionAttachment) *DispositionAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispositionAttachmentUpdate) SetUpdatedAt(v time.Time) *DispositionAttachmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DispositionAttachmentMutation object of the builder.
func (_u *DispositionAttachmentUpdate) Mutation() *DispositionAttachmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DispositionAttachmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispositionAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DispositionAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispositionAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispositionAttachmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dispositionattachment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispositionAttachmentUpdate) check() error {
	if _u.mutation.DispositionCleared() && len(_u.mutation.DispositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DispositionAttachment.disposition"`)
	}
	return nil
}

func (_u *DispositionAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dispositionattachment.Table, dispositionattachment.Columns, sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dispositionattachment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispositionattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DispositionAttachmentUpdateOne is the builder for updating a single DispositionAttachment entity.
type DispositionAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DispositionAttachmentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DispositionAttachmentUpdateOne) SetUpdatedAt(v time.Time) *DispositionAttachmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DispositionAttachmentMutation object of the builder.
func (_u *DispositionAttachmentUpdateOne) Mutation() *DispositionAttachmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DispositionAttachmentUpdate builder.
func (_u *DispositionAttachmentUpdateOne) Where(ps ...predicate.DispositionAttachment) *DispositionAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DispositionAttachmentUpdateOne) Select(field string, fields ...string) *DispositionAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DispositionAttachment entity.
func (_u *DispositionAttachmentUpdateOne) Save(ctx context.Context) (*DispositionAttachment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DispositionAttachmentUpdateOne) SaveX(ctx context.Context) *DispositionAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DispositionAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DispositionAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DispositionAttachmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dispositionattachment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DispositionAttachmentUpdateOne) check() error {
	if _u.mutation.DispositionCleared() && len(_u.mutation.DispositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DispositionAttachment.disposition"`)
	}
	return nil
}

func (_u *DispositionAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *DispositionAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dispositionattachment.Table, dispositionattachment.Columns, sqlgraph.NewFieldSpec(dispositionattachment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DispositionAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dispositionattachment.FieldID)
		for _, f := range fields {
			if !dispositionattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dispositionattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dispositionattachment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DispositionAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispositionattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
