// Code generated by ent, DO NOT EDIT.

package dispositionattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldUpdatedAt, v))
}

// DispositionID applies equality check predicate on the "disposition_id" field. It's identical to DispositionIDEQ.
func DispositionID(v uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldDispositionID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldTitle, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldPath, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldMimeType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldUpdatedAt, v))
}

// DispositionIDEQ applies the EQ predicate on the "disposition_id" field.
func DispositionIDEQ(v uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldDispositionID, v))
}

// DispositionIDNEQ applies the NEQ predicate on the "disposition_id" field.
func DispositionIDNEQ(v uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldDispositionID, v))
}

// DispositionIDIn applies the In predicate on the "disposition_id" field.
func DispositionIDIn(vs ...uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldDispositionID, vs...))
}

// DispositionIDNotIn applies the NotIn predicate on the "disposition_id" field.
func DispositionIDNotIn(vs ...uuid.UUID) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldDispositionID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldType, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContainsFold(FieldTitle, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContainsFold(FieldPath, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.FieldContainsFold(FieldMimeType, v))
}

// HasDisposition applies the HasEdge predicate on the "disposition" edge.
func HasDisposition() predicate.DispositionAttachment {
	return predicate.DispositionAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DispositionTable, DispositionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDispositionWith applies the HasEdge predicate on the "disposition" edge with a given conditions (other predicates).
func HasDispositionWith(preds ...predicate.Disposition) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(func(s *sql.Selector) {
		step := newDispositionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DispositionAttachment) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DispositionAttachment) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DispositionAttachment) predicate.DispositionAttachment {
	return predicate.DispositionAttachment(sql.NotPredicates(p))
}
